version: '3'
services: 
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tododb
    container_name: postgres-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nestjs:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: tusharchy/nest-and-postgres-application:latest
    environment: 
      - DB_TYPE=postgres
      - POSTGRES_HOST=postgres-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DB=tododb
      - POSTGRES_SYNC=false
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_PORT=5432
      - APP_EXPIRES=${APP_EXPIRES}
      - APP_PORT=3000
    ports: 
      - "3000:3000"
    container_name: nest-todo-app-be
    depends_on: 
      - db
    volumes: 
      - .:/app
      - /app/node_modules